### ISSUE TITLE
Filter on entries with links to games

### ISSUE THREAD

**Issue by lathomas64** [QuantumBox/blackgamedevs#107]
In service of the goal "buy their stuff" Maybe it would be worthwhile to have a way to filter based just on who has game links filled out.

**Comment by cattsmall** [comment]
Good idea, thank you! Will figure this out soon.

**Comment by zelgadis** [comment]
I'm gonna see about getting this working!

**Comment by cattsmall** [comment]
@zelgadis thank you!
