### ISSUE TITLE
Addition Request: Ronald Fontenot (Game Audio, 3D Modeling)

### ISSUE THREAD

**Issue by musicscj** [QuantumBox/blackgamedevs#119]
Website: https://ronaldsartandmusic.com/
Youtube: https://www.youtube.com/channel/UCXLLF1InpAW3ChZCWTmbYdw
Youtube: https://www.youtube.com/c/kidsvidsscj

Please consider adding me to your listing.  My name is Ronald Fontenot, pen name is Scott C. Johnson.  I create music and do 3D modeling (see my website under 3D)

**Comment by cattsmall** [comment]
Done! Website seems to be broken so I didn't add that. LMK if you have any other links you want added!
