### ISSUE TITLE
Addition Request: Dani Lalonders (Production, narrative design,public relations)

### ISSUE THREAD

**Issue by danilmao** [QuantumBox/blackgamedevs#127]
Name: Dani Lalonders
Twitter: https://twitter.com/danulmao
Instagram: https://www.instagram.com/dani.lmao/?hl=en
Head developer of Validate Game https://twitter.com/ValidateGame

Game: ValiDate: Struggling Singles in Your Area
Business: https://validategame.com/
Twitter: https://twitter.com/ValidateGame
Patreon: https://www.patreon.com/validategame
Press kit: https://validategame.com/#pressinfo

Image: 
![image](https://user-images.githubusercontent.com/66279744/83459159-7282a380-a429-11ea-8405-151eaefdf421.png)

**Comment by cattsmall** [comment]
Done!
