### ISSUE TITLE
Addition: Quinn George

### ISSUE THREAD

**Issue by quinnsea** [QuantumBox/blackgamedevs#131]
## Name 
Quinn George

## Image
https://i.imgur.com/5lZpsZf.jpg

## Skills 
- User interface design
- Copywriting
- Narrative design

## Location 
United States

## Websites 
(Add or remove any you don't need)

### Personal 

- Website https://quinnseas.wixsite.com/portfolio 
- Twitter https://twitter.com/quinn_killick

### Business 

- Website https://koimarina.itch.io/
- Twitter https://twitter.com/koimarina

## Games 
(Add or remove any you don't need)
- Treehouse Defenders https://yulind.itch.io/treehouse-defenders
- Baleen https://koimarina.itch.io/baleen
- Aspen https://koimarina.itch.io/aspen

**Comment by cattsmall** [comment]
Thanks for submitting this request! I've implemented it and your information will be included in the next update today. 😄
