### ISSUE TITLE
Addition: Hermann Kayode

### ISSUE THREAD

**Issue by airman4** [QuantumBox/blackgamedevs#132]
## Name 
Hermann Kayode

## Image
https://www.instagram.com/p/CAdUw0OBojW/

## Skills 

- Game design
-
- User interface design
- 
-
- 
- 
- 
- 
- 
- Game art 

## Location 
Senegal

## Websites 
https://www.instagram.com/hermannkayode/

### Personal 
African artist from Benin currently living in senegal
I do game arts and indie games and as well 2d animated films

- Website https://www.artstation.com/airman4
- Twitter https://twitter.com/lenneth4
- Facebook https://web.facebook.com/hermann.P.S.kayode
- Instagram https://www.instagram.com/hermannkayode/
- Youtube https://www.youtube.com/user/orinn24
- Patreon https://www.patreon.com/airman4

### Business 

- Website https://www.artstation.com/airman4
- Twitter https://twitter.com/lenneth4
- Facebook https://web.facebook.com/hermann.P.S.kayode
- Instagram https://www.instagram.com/hermannkayode/
- Youtube https://www.youtube.com/user/orinn24
- Patreon https://www.patreon.com/airman4

## Games 
(Add or remove any you don't need)
-Junk Heaven artpack for coders https://www.unrealengine.com/marketplace/junk-heaven-art-assets/
-Hammer time https://airman4.itch.io/hammertime
- Star and light first version (2012 ) https://airman4.itch.io/star-and-light-10
- GAME_NAME_HERE http://link-here.com

**Comment by cattsmall** [comment]
Thanks for submitting this request! I've implemented it and your information will be included in the next update today. 😄

**Comment by cattsmall** [comment]
Note: I couldn't find the actual image source for that Instagram image so I used this: https://cdnb.artstation.com/p/assets/images/images/026/481/237/large/hermann-kayode-oya.jpg?1588883606

**Comment by airman4** [comment]
Thanks a lot cattsmall and awesome idea !
I hope the linbk for the image works
