### ISSUE TITLE
Edit: Sylverstone Khandr

### ISSUE THREAD

**Issue by Sylverstone14** [QuantumBox/blackgamedevs#138]
## Name
Sylverstone Khandr

## Details about edit request
It's been quite a while since my entry has been updated, so I'd like to make sure that all the links are correct, among other things.

## Image
https://i.imgur.com/prqg3oF.png

## Skills
Remove:
- Game audio
- Programming

## Location
United States

## Websites 
(updated + new)

- Website http://sylversedge.com
- Twitter https://twitter.com/Sylverstone14
- Twitch https://twitch.tv/SylverstoneKhandr
- itch.io https://itch.io/SylverstoneKhandr
- YouTube https://youtube.com/SylverstoneKhandr
- Ko-fi https://www.ko-fi.com/SylverstoneKhandr

**Comment by cattsmall** [comment]
Thanks for submitting this request! I've implemented it and your information will be included in the next update today. The image you included was pretty small, so I used this one to show off your work: https://payload.cargocollective.com/1/18/580937/12074262/prt_280x188_1481867423_2x.png

**Comment by Sylverstone14** [comment]
Hey Catt, I totally realized I sent a really small image!

I have this larger version here!
https://i.imgur.com/RihqJ9B.png
