### ISSUE TITLE
Addition: Cedric J Adams

### ISSUE THREAD

**Issue by Cedrissimo** [QuantumBox/blackgamedevs#140]
{
      "name": "Cedric J Adams",
      "image": "http://wherecardsfall.com/img/screenshots/03_structures.jpg",
      "skills": [
         "game animation",
      ],
      "location": "United States",
      "websites": {
         "personal": [
            [
               "Twitter",
               "https://twitter.com/SkinnyFoxford/"
            ],
            [
               "Instagram",
               "https://www.instagram.com/foxfordfailure"
            ],
            [
               "Instagram",
               "https://www.instagram.com/skinnybonsai"
            ]
         ],
         "business": [
            [
               "Website",
               "https://cedricjadams.com"
            ]
         ]
      },
      "games": [
         [
            "Where Cards Fall",
            "http://wherecardsfall.com/"
         ]
      ]
   }

**Comment by Cedrissimo** [comment]
**I tried going the github route but source tree wouldn't allow any kind of push or pull request. Normally, I just push changes to branches but I understand the need to wall off changes when multiple people are editing a single json file.

I also added the skill for game animation as that was missing**

**Comment by cattsmall** [comment]
thank you for your submission!
