### ISSUE TITLE
Available Roles

### ISSUE THREAD

**Issue by awardjr** [QuantumBox/blackgamedevs#144]
So I’ve heard from companies wanting to share roles with people on the site and would like to open a discussion on if there’s a good solution for that which can be done on this site or what those with open roles should do to reach out to people here.

However I can see this not necessarily being within scope of this site but having a list of companies that support the cause and actively want to hire from the list could be useful in some form. 

Apologies for not fleshing out ideas more as I just want to put things down to start the conversation as not to forget it

**Comment by cattsmall** [comment]
It's a cool idea but it's outside the core use cases for the site (we want to highlight people to hire and buy from). Job sites also require a lot of maintenance. Going to close this one.
