### ISSUE TITLE
Hi all,

### ISSUE THREAD

**Issue by GeeEn** [QuantumBox/blackgamedevs#150]
Sorry to bother you, but I'd like to be added to this list of developers. 
I use sourcetree GUI and bitbucket, and I can't get my setup working with yours.
Heres the changes for the companies.json file:

  {
    "name": "GN Games",
    "image": "http://www.gngames.co.uk/wp-content/uploads/2020/04/GNSplashScreen.png",
    "location": "United Kingdom",
    "websites": 
    [
      [
        "Website",
        "http://GNGames.co.uk"
      ],
      [
        "Twitter",
        "https://twitter.com/developmentgn"
      ],
      [
        "Youtube",
        "https://www.youtube.com/channel/UCMY-fsf37xfQgdLObCR2cBQ"
      ]
    ],
    "games": 
    [
      [
        "Stella Spella",
        "https://www.microsoft.com/store/apps/9PFMCGTCVVH4"
      ],
      [
        "Nubian Jak",
        "https://play.google.com/store/apps/details?id=com.GNDevelopment.NubianJakUS"
      ]
    ]
  }

Many thanks guys.
Aubs

**Comment by cattsmall** [comment]
Thanks for submitting this request! I've implemented it and your information will be included in the next update today. 😄

**Comment by GeeEn** [comment]
Thanks Catt.
Keep up the good work!
Aubs
