### ISSUE TITLE
Addition: Nickolas David Anderson

### ISSUE THREAD

**Issue by MisterNancy** [QuantumBox/blackgamedevs#168]
## Name
Nickolas David Anderson 

## Skills
- Game design
- User interface design
- Production
- Marketing
- Quality assurance
- Publishing

## Location
United States of America 

## Websites
N/A 

### Personal

- Twitter https://twitter.com/anansi_zero
- LinkedIn https://www.linkedin.com/in/nicoanderson/

### Business
N/A

## Games
(Add or remove any you don't need)
- Amoebattle
- Baby & Me: Modern Mom
- Bad meets Evil
- Boom Blox
- Command & Conquer 3: Kane's Wrath
- Command & Conquer: Red Alert 3
- Crysis
- Fast & Furious: Takedown
- G.I. Joe Rise of Cobra
- Genies & Gems
- Gold Miner Rush
- Gold Miner World
- Jaws.io
- Medal of Honor: 2010
- Medal of Honor: Airborne
- Medal of Honor: Frontline
- Mercenaries 2: World in Flames
- Monopoly Streets
- Need for Speed Hot Pursuit
- Paint Monsters
- Panda Jam
- Skate 3
- Slots Dreamland
- Smarty Pants
- Sugar Smash: Book of Life
- Tetris PSN
- The Saboteur

**Comment by annarankin** [comment]
Hi @MisterNancy! I'm happy to create a PR to add you to the index 😃  The maintainers of the site have asked folks to limit their games to 3 max - do you have 3 in particular you'd like to spotlight? If so, links to the websites for those games would also be excellent. Thanks!

**Comment by MisterNancy** [comment]
This is hard. I'll choose the most significant to me.

Medal of Honor 2010

The Saboteur

Genies & Gems
