### ISSUE TITLE
List of people from The Coli

### ISSUE THREAD

**Issue by cattsmall** [QuantumBox/blackgamedevs#17]
http://www.thecoli.com/threads/black-people-working-in-the-video-game-industry.237512/

Let's go through and see if we missed anyone.

**Comment by cattsmall** [comment]
**People**
Ajari Wilson
http://www.adversarygames.com/
https://twitter.com/adversarygames
https://twitter.com/AjariWilson

Anne Shongwe
http://www.afroes.com/
https://twitter.com/afroesgames
https://twitter.com/anneshongwe

Des Gayle
http://alteredgene.london/
https://twitter.com/Altered_Gene
https://twitter.com/Kid_Desimo

Andy James Nicholls
https://twitter.com/AndyTwiddly

Audley Gordon
http://agindie.tumblr.com/
https://twitter.com/AGIndie

Ventroy Rolle
http://www.bigvgames.com/
https://twitter.com/TroyGotCode

Brandon J. Bruce
http://sunhutzu.carbonmade.com/
https://twitter.com/sunhutzu

Bruce Johnson
http://neonarkade.com/
https://twitter.com/neonarkade

Bryan Williams
https://twitter.com/TruBWill

Bryson Whiteman
http://www.sokay.net/
http://www.sonofbryce.com/
https://twitter.com/sokaynet
https://twitter.com/sonofbryce

CelleC Games Inc.
http://www.cellecgames.com/
https://twitter.com/CelleCgames

Chase Bethea
http://chasebethea.com/
https://twitter.com/chasebethea

Christopher A. Butler
http://ninjaegg.com/
https://twitter.com/zionviller

Chris Wells
https://twitter.com/BK_WallabyJoe

Damien A. Morris
https://twitter.com/DamienAM

Darryl Johnson
https://twitter.com/USERpick05

Davon Marquis Sanders
https://twitter.com/gmzcharlotte

Ahmed Abdullah
http://www.decoygames.com/
https://twitter.com/DecoyGames
https://twitter.com/BR0thaMAN

Demond Rogers
https://twitter.com/SuperBluez

Derek L. Manns
http://www.derekmanns.com/
https://twitter.com/GameDesignDude

Derek Smart
http://www.dereksmart.org/
https://twitter.com/dsmart

Jay Adeloye
http://dropdeadinteractive.com/
https://twitter.com/DropDeadInt
https://twitter.com/BytesOfChicken

Duckbridge
http://duckbridge.nl/
https://twitter.com/Duckbridge
https://twitter.com/marcianoviereck

Ebrima Leigh
https://twitter.com/ebrima_leigh

Endless Fluff
http://www.endlessfluff.com/
https://twitter.com/EndlessFluff

Evie Powell
http://www.eviemakesgames.com/
https://twitter.com/ParasiteEvie

Frank Silas
http://www.franksilas.com/
https://twitter.com/FrankSilas

Melissa Avery-Weir
http://futureproofgames.com/
https://twitter.com/PlayFutureProof
https://twitter.com/averymd

Lavon Woods
http://gamebuilderstudio.com/
https://twitter.com/gamebuilders
https://twitter.com/LavonWoods

Gaming Pixie
http://games.gamingpixie.com/
https://twitter.com/GamesByPixie
https://twitter.com/GamingPixie

Graham Reid
http://www.grahamreid.tv/
https://twitter.com/GrahamOfLegend

Greg Goodson
https://goodson.carbonmade.com/
https://twitter.com/jetgreguar

Gregory Jean-Baptist
https://twitter.com/black_collar_GR

Mat Broome
http://www.heromachinestudios.com/
http://www.matbroome.com/
https://twitter.com/Mbroome1

Hillmon Ancrum
https://twitter.com/hillmon_
http://glorft.tumblr.com/

Hoop Somuah
343 Industries
http://hoopsomuah.com/
https://twitter.com/hoopsomuah

Greg Johnson
http://humanaturestudios.com/
https://twitter.com/HumanatureGames
https://twitter.com/ToejamGreg

Frenel Djossa
http://www.ignov8.com/
https://twitter.com/FrenelDjossa

Justin Woodward
http://www.interabangent.com/
https://twitter.com/icjman

Isaac Nichols
http://www.dronezerogravity.com/
https://twitter.com/IsaacThreedart

Jacob Mooney
http://jacobdmooney.com/
https://twitter.com/JacobDMooney

Jae Lee
http://www.kingsofkungfu.com/
https://twitter.com/KingsOfKungFu

Jason Coker
http://gunsupgame.com/en-us
https://twitter.com/Bomangani

Jason Paul
Nauty Dog
https://twitter.com/jmpaul

Jermaine Belcher
http://batenkaitosorigins.wix.com/jermaineb
https://twitter.com/jermaineatl

Bradston Henry
https://twitter.com/TheJILGames
https://twitter.com/TheGospelGamer

Joe Palmer
http://irongalaxystudios.com/
https://twitter.com/Jet_Black

John Davis
https://twitter.com/p0rk1ns

Joshua Parker
https://twitter.com/BossBlackDante

Kidando
http://kidando.net/
https://twitter.com/Kidando

Kieron White
https://kwhite3d.carbonmade.com/
https://twitter.com/KieronWhite3d

K.L. Smith
https://twitter.com/arCtyC

Kojo Kumah
http://www.kojokumah.com/
https://twitter.com/KojoKumah

Kola Studios
http://kolastudios.com/
https://twitter.com/kolastudios
https://twitter.com/dokalanyi
https://twitter.com/zedjasper

Kuluya
http://www.kuluya.com/
https://twitter.com/KuluyaGames

Lauren E. Scott
http://laurenescott.com/
https://twitter.com/Lauren_E_Scott

Lee Hinds
https://twitter.com/LeeHinds91

Leonard J. Paul
http://www.videogameaudio.com/
https://twitter.com/VideoGameAudio

Leti Arts
http://letiarts.com/
https://twitter.com/letiarts
https://twitter.com/eyramtawia

Lisette Titre
http://www.lisettetitre.com/
https://twitter.com/zette16

Lucky Shot Media
http://luckyshotmediallc.com/
https://twitter.com/Southerndeep

MABManZ
http://mabmanz.com
https://twitter.com/MABManZ

MALIYO Games
https://www.maliyo.com/
https://twitter.com/maliyogames
https://twitter.com/lexyhugo

Marcus Terrell
https://twitter.com/DrHadji

Markus Heinel
http://www.markusheinel.com/
https://twitter.com/markusheinel

Matthew Findlater
http://www.matthewfindlater.com/
https://twitter.com/ieatgames

Maximum Crash
https://maximumcrash.carbonmade.com/
https://twitter.com/Maximum_Crash

Michel Nkuindja
http://www.nkuindja.me/
https://twitter.com/nkuindja

Mike Adebajo
http://www.weseeinpixels.com/
https://twitter.com/L1keMike

Mike Murray
http://king9999.itch.io/
https://twitter.com/MikeADMurray

More Fire Games
http://morefiregames.com/
https://twitter.com/MoreFireGames
https://twitter.com/SyidMassiah
https://twitter.com/KeemMrDanks
https://twitter.com/roniquewright
https://twitter.com/Mr_Davis27

Nicole Anetra Lewis
https://twitter.com/nikkianetra

NostalgiCO
http://robscorner.tumblr.com/
https://twitter.com/RobaatoX

Notion Games
http://notiongames.com/
https://twitter.com/NotionGamesLLC
https://twitter.com/DatBoiDrew

Nuchallenger
http://anewchallengerawaits.com
https://twitter.com/anuchallenger

Ondayo
http://www.ataxiathegame.com/
https://twitter.com/OndayoLLC
https://twitter.com/Kildros

Paul Davey
http://www.mattahan.com/
https://twitter.com/mattahan

Paul LaCen
https://twitter.com/Rykoshet

PawByte
http://pawbyte.com/
https://twitter.com/Pawbyte

PinkTreeLeaf
http://www.pinktreeleaf.com/
https://twitter.com/Pinktreeleaf

Pixiro
http://www.pixiro.com/
https://twitter.com/PixiroGames
https://twitter.com/YannickNiamkey

Polkritude
http://kpolkmusic.squarespace.com/
https://twitter.com/polkritude

PolyKnight Games
http://polyknightgames.com/
https://twitter.com/ericbrodie

Power On Games
http://pogky.com/
https://twitter.com/ktp4life

pyun-pyun
http://pyun.itch.io/
https://twitter.com/pyunpyunchan

R. Lateef
http://www.rlateef.com/
https://twitter.com/hypevoltage

Ramone Russell
https://twitter.com/modnationracers

Ray Batts
https://twitter.com/Ray_Batts

Reggie Fils-Aimé
http://www.nintendo.com/

ReJean DuBois
http://kasai.deviantart.com/
https://twitter.com/LeJeanX3

Rekcahdam
http://www.rekcahdam.com/
https://twitter.com/Rekcahdam

Revelation Interactive
http://www.revelation-interactive.com/
https://twitter.com/RIGames
https://twitter.com/Revel8n
https://twitter.com/kokushibyou2

Richard Terrell
http://critical-gaming.com/
http://www.designoriented.net/
https://twitter.com/KirbyKid

Richie Branson
http://richiebranson.com/
https://twitter.com/richiebranson

Rokashi Edwards
http://rokashi.itch.io/
https://twitter.com/rokashi

Ron Jones
https://sites.google.com/site/ronjonestheartist/
https://twitter.com/The_RonJones

Sean Bellinger
https://seanbellinger.carbonmade.com/
https://twitter.com/Locutus3d

Sean R. Scott
http://gamedevmasters.com/
https://twitter.com/seanrscott

Shawn Pierre
http://www.shawnpierre.com/
http://www.origaminc.com/
https://twitter.com/ShawnPierre
https://twitter.com/origaminc

Silentrivr
www.silentrivr.com/
http://www.rob3rtmorrison.com/
https://twitter.com/SilentRivr
https://twitter.com/b0b3rt

Sleight Of Hand Studios
http://www.sleightofhandstudios.net/
https://twitter.com/SOHStudios
https://twitter.com/CPaul_Parker

SolarLune
http://solarlune.com/
https://twitter.com/SolarLune

Somara Atkinson
http://somaraatkinson.com/
https://twitter.com/SomaraA

Spray N Pray Studios
https://twitter.com/S_N_P_Studios
https://twitter.com/KyntonStephens

Spritewrench
http://spritewrench.com/
https://twitter.com/SpriteWrench

Sterlyng Powell
http://www.sterlyngpowell.com/
https://twitter.com/sterbo708

Terrance Smith
http://hackerferret.com/
https://twitter.com/musicm122

Tim Lewinson
https://twitter.com/VancouverTim

Jamal Seaton
http://www.titointeractive.com/
https://twitter.com/titointeractive
https://twitter.com/JamalSeaton

Tony Barnes
http://www.twitchfactor.com/
https://twitter.com/Twitchfactor

Tony Yotes
http://www.yotesgames.com/
https://twitter.com/TonyYotes

Tramell Ray Isaac
http://bosskey.com/
https://twitter.com/PS_TRay

Tristion Edison
http://www.inkjuse.com/
https://twitter.com/InkJuse

Troy D. Patterson
http://www.troydpatterson.com/
https://twitter.com/MrTroy

Warren Price
Ubisoft
https://twitter.com/WarrenPrice

Wayman Harris
http://www.waymanapps.com/
https://twitter.com/WaymanApps

Wilbert Roget, II
http://www.rogetmusic.com/
https://twitter.com/WilbertRoget

**Companies**

Algorythmic Studios
http://www.algorythmicstudios.com/
https://twitter.com/jaywalkar_
https://twitter.com/Striderzet

White Guardian Studios
http://demonsrevenge.com/
https://twitter.com/_demonsrevenge_

FourTwoThree Studios
http://fourtwothreestudios.com/
https://twitter.com/HipHopBerserker

Gamsole
http://www.gamsole.com/
https://twitter.com/GamsoleStudio

Gnovahex Computing
https://twitter.com/Gnovahex
https://twitter.com/dooplejoy

**Comment by CNIAngel** [comment]
There are so many registered deletions in my pull request because I ran the HTML through a formatter :/ Sorry in advance for the confusion.
