### ISSUE TITLE
Git Submission Instructions

### ISSUE THREAD

**Issue by bharrislo** [QuantumBox/blackgamedevs#190]
**Is your feature request related to a problem? Please describe.**
I spent almost 2 hours trying to submit my addition via github, but could not create a pull request.

**Describe the solution you'd like**
In the ReadMe doc, instead of simply saying "create a pull request" please provide more detailed instructions or links with instructions to create a pull request.

**Describe alternatives you've considered**
I tried creating a pull request without committing or pushing, after committing, and after committing to a different branch. Committing on the original branch (2018 architecture) and to a branch I created myself (then deleted) both opened the menu to compare branches, but then I got an error message when I said I wanted to create the request. Trying to create a request without committing or pushing simply said there were no changes; online research did not help me solve the problem. 

**Additional context**
I use Sourcetree primarily, but was trying out a combination of the app and the webpage to try and create the pull request. Attached is the error message I got in sourcetree after trying to commit to the 2018 branch then create a pull request.
![Screenshot (394)](https://user-images.githubusercontent.com/43525971/84953685-f68f8900-b0c1-11ea-80ac-5a92139051ac.png)

**Comment by MaximumCrash** [comment]
@cattsmall I'm going to close this and make a new issue on improving entry submission ux. This issue was sort of fixed by the issue templated back in the summer, but we can explore easier options.
