### ISSUE TITLE
Adding myself and fellow teammate from Zapling Studios!

### ISSUE THREAD

**Issue by qball13z** [QuantumBox/blackgamedevs#2]
Name: Quintin Rodriguez-Harrison
Twitter: @qball13z
Company: Zapling Studios (www.zaplingstudios.com)
Game: Justice Royale (Coming soon to iOS!)

Name: Brandon Perry
Twitter: @BranPerry
Company: Zapling Studios (www.zaplingstudios.com)
Game: Justice Royale (Coming soon to iOS!)

Thanks guys! Really appreciate what you're doing with the site and spreading awareness! Keep it up!

**Comment by cattsmall** [comment]
We got y'all! Thank you, and keep being awesome! MAKE ALL THE THINGSSS

**Comment by qball13z** [comment]
Thank you! Looks like the URLs for www.zaplingstudios.com aren't working, currently you have them going here: http://www.blackgamedevs.com/www.zaplingstudios.com , which is a 404. :)

Thanks again.

**Comment by awardjr** [comment]
Whoops. Fixed that. Thanks for catching that!
