### ISSUE TITLE
Carrill Munnings (add to list)

### ISSUE THREAD

**Issue by Carrill** [QuantumBox/blackgamedevs#31]
Hello,

I found this tag on Twitter and I wanted to add myself to this list. My name is Carrill Munnings and I'm a black game developer who's also a trans woman. I made a game called Perdition and I'm currently working on a follow-up project called Trinity. I'm really looking to get more followers so that I'll have a larger network and so that I'll one day be able to support myself as a full-time indie game developer.

https://twitter.com/carrillgamedev
http://carrill.newgrounds.com/
http://carrillmunnings.com/

**Comment by cattsmall** [comment]
Success! Thank you and good luck <3
