### ISSUE TITLE
Developers != Programmers

### ISSUE THREAD

**Issue by justplainc** [QuantumBox/blackgamedevs#55]
First of all, I appreciate Catt Small even more for finally making me reset my GitHub password after 2 whole years, I only signed in once!

While browsing the site I noticed that there was no apparent distinction between Programmer and Developer. I briefly took the issue to Ms.Small [via Twitter](https://twitter.com/cattsmall/status/700533926129831936) and was directed to restate my case here. While her initial point was sound, being that developers == programmers, I'll have to disagree.

The term development directly correlates to the overall process of development. So an artist creating art is developing assets for a game, in development. They would therefore also be considered a developer by definition. This obfuscation does a disservice to those who consider themselves strictly programmers, especially considering the distinction has been made elsewhere on the list. I'm requesting that a separate category be made to distinguish Programmers from the loosely based term "developer".

Thanks,

Chris "Doop" LeJohn // [@dooplejoy](https://twitter.com/dooplejoy)

**Comment by waxxxd** [comment]
My personal distinction is - programmers make use of -- as in make use of an api or **program** a PLC --. Developers create and thus create/develop api's or frameworks.

**Comment by mychalwillis** [comment]
I agree. A Programmers category would be good for people who are primarily programmers.

**Comment by lathomas64** [comment]
creating apis and frameworks is still programming. That is an odd and seemingly extremely arbitrary distinction.

**Comment by mychalwillis** [comment]
Is a programmer section going to be added? I am going to do a pull request to add some people and I will wait until the programmer section is added if it's going to be added. 

Or I can do it myself in the pull request and add some people that I know are primarily programmers.

**Comment by cattsmall** [comment]
Sorry, it was a busy 9 months. I'll change the name to "Programmer" if this helps to clarify the issue. Thanks everyone!

**Comment by cattsmall** [comment]
Actually

**Comment by cattsmall** [comment]
Hey all – I'll add a section for programmers so that strict programmers have a place to put themselves. Thank you, and sorry for the silence! It's been a busy 9 months.
