### ISSUE TITLE
Alteration of Sylverstone Khandr's Listing + Links

### ISSUE THREAD

**Issue by Sylverstone14** [QuantumBox/blackgamedevs#56]
Would it be possible to move my listing from the Art & Animation section over to the Multi-Skilled section?

Also, the itch.io link is broken (_no www. needed_), and I'm requesting that the third link be changed from my old blog to my portfolio site (http://www.cargocollective.com/SylversEdge).

Thanks!
- _Sylver_

**Comment by awardjr** [comment]
done, sorry it took so long
