### ISSUE TITLE
Addition Request.

### ISSUE THREAD

**Issue by Jhilton94** [QuantumBox/blackgamedevs#65]
Hey, call it narcissism, but I'll call it pride. Can I put myself on here? I'm a black game dev working at indie game company En House Studios on our current project, GLITCHED. Information about our company and game can be found here on our Kickstarter page https://www.kickstarter.com/projects/enhousestudios/glitched/description (the campaign was over several months ago we received nearly 1000% of our funding goal.) I personally work on game design, character and world design, dialogue and story, as well as writing and producing the music.

My name is Justin Hilton
I am 22 years old. I live in Chicago, Illinois and as far as I'm concerned I am a black game dev.

**Comment by cattsmall** [comment]
Thanks, Justin! You've been added. If you have any personal links you want added as well, let us know!
