### ISSUE TITLE
Entry Change Request

### ISSUE THREAD

**Issue by AsixJin** [QuantumBox/blackgamedevs#66]
Firstly thank you for adding me to this list...I didn't know it existed until two weeks ago. I only want to request that the website that is currently linked to my entry to be changed to www.AsentrixStudios.com

I would fork and fix myself, but I don't have time and don't want to forget. However if I do it, I'll notate that on this issue.

**Comment by AsixJin** [comment]
I have made a pull request with my changes - #67

**Comment by cattsmall** [comment]
Thanks again for the pull request!
