### ISSUE TITLE
Missing Dain Saint

### ISSUE THREAD

**Issue by gl326** [QuantumBox/blackgamedevs#7]
cipherprime.com
Music.dainsaint.com

Game designer, musician, programmer

**Comment by cattsmall** [comment]
Thanks for suggesting them @gl326!

Dain Saint - http://dainsaint.com/ and http://www.cipherprime.com/

Any other links/projects we should include?

**Comment by cattsmall** [comment]
Nevermind, spotted the ones you listed. Sorry! Adding now.
