### ISSUE TITLE
New devs to add! From Lauren!

### ISSUE THREAD

**Issue by lescott-games** [QuantumBox/blackgamedevs#71]
Here are the entries I posted on Twitter for the Programmer section! :)

https://twitter.com/RaySJoshua_
https://www.linkedin.com/in/scott-anderson-a31b372
https://twitter.com/Wadarass
https://www.linkedin.com/in/jameka-march-8ab0a647

I'm sure there are many more! :)

**Comment by cattsmall** [comment]
Thank you! Will post the in our next set of updates.
