### ISSUE TITLE
Mattieau (Manikk) St.Cyr - (Art & Animation/ Audio / Multi-talented) 

### ISSUE THREAD

**Issue by Manikktheone** [QuantumBox/blackgamedevs#79]
Hi, here are my links. 
https://mattstcyr.carbonmade.com/ 
https://vimeo.com/manikk
https://www.instagram.com/manikkrealm/
www.manikkrealm.com
https://mattanimates.tumblr.com/
https://soundcloud.com/mattieau

**Comment by cattsmall** [comment]
Done!
