### ISSUE TITLE
Jordan Sparks - Art & Animation | Game Design & Development | UI & UX (Multitalented)

### ISSUE THREAD

**Issue by SuperSparkplug** [QuantumBox/blackgamedevs#85]
<li>Jordan Sparks - <a href="http://GrindSpark.com" target="_blank">GrindSpark.com</a>, <a href="http://twitter.com/SuperSparkplugs" target="_blank">@SuperSparkplugs</a>,  <a href="http://supersparkplug.deviantart.com" target="_blank">DeviantArt</a>, <a href="http://SparkComic.com" target="_blank">Spark Comics</a>, <a href="http://Patreon.com/JSparks" target="_blank">Patreon</a>, <a href="https://www.facebook.com/SparkComics/" target="_blank">Facebook</a>
</ul>

**Comment by cattsmall** [comment]
Done!
