### ISSUE TITLE
Derrick Fields - Art & Animation - Multitalented

### ISSUE THREAD

**Issue by Daerhyk** [QuantumBox/blackgamedevs#88]
Derrick Fields - Art & Animation - Multitalented
https://www.wakingoni.com

Company - Waking Oni

Games
https://www.onsenmaster.com/

Twiiter
@WakingOni
@OnsenMasterGame
Instagram
@WakingOni
Facebook
WakingOni - https://www.facebook.com/wakingoni
Onsen Master - https://www.facebook.com/onsenmastergame/

**Comment by cattsmall** [comment]
Done!
